service: graphql
provider: aws
runtime: nodejs4.3
plugins:
  - serverless-webpack

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
         path: graphql
         method: post
